export interface ColorPalette {
    baseBackground: string,
    baseBackgroundInactive: string,
    baseBackgroundShadow: string,
    baseBackgroundShadowInactive: string,
    baseBorder: string,
    baseBorderInactive: string,
    baseText: string,
    baseTextInactive: string,
    baseTextTitle: string,
    baseTextTitleInactive: string,
    baseTextSubtle: string,
    baseTextSubtleInactive: string,

    primaryBackground: string,
    primaryBackgroundInactive: string,
    primaryBackgroundShadow: string,
    primaryBackgroundShadowInactive: string,
    primaryBorder: string,
    primaryBorderInactive: string,
    primaryText: string,
    primaryTextInactive: string,
    primaryTextTitle: string,
    primaryTextTitleInactive: string,
    primaryTextSubtle: string,
    primaryTextSubtleInactive: string,

    secondaryBackground: string,
    secondaryBackgroundInactive: string,
    secondaryBackgroundShadow: string,
    secondaryBackgroundShadowInactive: string,
    secondaryBorder: string,
    secondaryBorderInactive: string,
    secondaryText: string,
    secondaryTextInactive: string,
    secondaryTextTitle: string,
    secondaryTextTitleInactive: string,
    secondaryTextSubtle: string,
    secondaryTextSubtleInactive: string,

    successBackground: string,
    successBackgroundShadow: string,
    successBorder: string,
    successText: string,

    warningBackground: string,
    warningBackgroundShadow: string,
    warningBorder: string,
    warningText: string,

    dangerBackground: string,
    dangerBackgroundShadow: string,
    dangerBorder: string,
    dangerText: string,

    infoBackground: string,
    infoBackgroundShadow: string,
    infoBorder: string,
    infoText: string,
}

export interface ColorTheme {
    name: string,
}
